linux_task:
  container:
    image: aquova/songbird:1.0

  build_script:
    - make gui
    - mv gui/target/release/songbird_gui .
    - mv songbird_gui songbird_linux

  songbird_artifacts:
    path: songbird_linux

osx_task:
  osx_instance:
    image: catalina-base

  setup_script:
    - brew update
    - brew install rust

  build_script:
    - make gui
    - mv gui/target/release/songbird_gui .
    - mv songbird_gui songbird_mac

  songbird_artifacts:
    path: songbird_mac

win_task:
  container:
    image: aquova/songbird:1.0

  build_script:
    - make windows
    - mv gui/target/x86_64-pc-windows-gnu/release/songbird_gui.exe .
    - mv songbird_gui.exe songbird_win.exe

  songbird_artifacts:
    path: songbird_win.exe

wasm_task:
  container:
    image: aquova/songbird:1.0

  build_script:
    - make wasm

  package_script:
    - zip -r songbird_wasm.zip web

  songbird_artifacts:
    path: songbird_wasm.zip
